name: Check package changed

description: Checks if the given package has changes against main.
inputs:
  package-name:
    required: true
    description: Path to the package to check.
  command:
    required: true
    description: The command to attempt to run.

runs:
  using: composite
  steps:
    - name: Setup PNPM
      uses: ./.github/actions/setup-packages
      if: ${{ inputs.node-version != 'true' }}
      with:
        node-version: ${{ inputs.node-version }}

    - name: Run ${{ inputs.command }}
      shell: bash
      run: pnpm run --filter "${{ inputs.package-name }}[origin/main]..." --fail-if-no-match ${{ inputs.command }}
