changesetIgnorePatterns:
  - "**/scripts/*"
  - "**/out/*"
  - "*.md"
  - .github/*

compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmPublishAccess: public

yarnPath: .yarn/releases/yarn-4.5.1.cjs
